# Generated by Django 5.2.6 on 2025-10-10 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, through='tasks.UserTask', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
